// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHp06XE_yvgmfTBRHWbRMCLureFzFdx9I',
    appId: '1:402583185168:web:8fd036d4433e4a66f82795',
    messagingSenderId: '402583185168',
    projectId: 'blog-app-4f5df',
    authDomain: 'blog-app-4f5df.firebaseapp.com',
    storageBucket: 'blog-app-4f5df.firebasestorage.app',
    measurementId: 'G-VCT3WEXHEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDST0zg1ygIv4dxnP0vHEGyXMqvgPYC_Zw',
    appId: '1:402583185168:android:7325a83a1528104bf82795',
    messagingSenderId: '402583185168',
    projectId: 'blog-app-4f5df',
    storageBucket: 'blog-app-4f5df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpD-rcSo2VoKfXkxIZqAr54K01aXOooPc',
    appId: '1:402583185168:ios:72d6d289beb86668f82795',
    messagingSenderId: '402583185168',
    projectId: 'blog-app-4f5df',
    storageBucket: 'blog-app-4f5df.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpD-rcSo2VoKfXkxIZqAr54K01aXOooPc',
    appId: '1:402583185168:ios:72d6d289beb86668f82795',
    messagingSenderId: '402583185168',
    projectId: 'blog-app-4f5df',
    storageBucket: 'blog-app-4f5df.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHp06XE_yvgmfTBRHWbRMCLureFzFdx9I',
    appId: '1:402583185168:web:af88110de42e2eabf82795',
    messagingSenderId: '402583185168',
    projectId: 'blog-app-4f5df',
    authDomain: 'blog-app-4f5df.firebaseapp.com',
    storageBucket: 'blog-app-4f5df.firebasestorage.app',
    measurementId: 'G-EWFL55XMTE',
  );
}
